### ISSUE TITLE
Sous titre saison > 10

### ISSUE THREAD

**Issue by yanoutt** [spikto/SoustitreDownloader#10]
Bonjour,
Je reviens vers toi car je n'arrive pas a faire télécharger des sous titres avec une saison a 2 chiffres.
Une idée?

**Comment by spikto** [comment]
Ok, je fais des tests et je te dis, si tu as le nom du fichier qui pose problème je vérifierai également s'il y a pas d'autres problèmes

**Comment by yanoutt** [comment]
NCIS.1218.hdtv-lol.mp4

**Comment by spikto** [comment]
Salut, désolé pour le retard, j'ai rajouté la correction et testé avec ton nom de fichier, maintenant pour moi ça marche.
