### ISSUE TITLE
Episode avec un nombre

### ISSUE THREAD

**Issue by yanoutt** [spikto/SoustitreDownloader#11]
J'ai des soucis avec les series suivantes:
castle.2009.719.hdtv-lol
the.flash.2014.117.hdtv-lol
Sachant que l'une se trouve en "castle" simple et l'autre en "the flash (2014)" sur addicted.
J'ai suivit un peu le programme et le probleme est que tu cherches les saisons et episodes avant le cleanseries.

J'ai le temps, ne t'en fait pas!

**Comment by yanoutt** [comment]
Je relance. As-tu pu chercher le pb?

**Comment by spikto** [comment]
Voila j'ai corrigé le problème, reteste et tiens moi au courant.
Désolé pour l'attente.
