### ISSUE TITLE
Page not found.

### ISSUE THREAD

**Issue by Kazfr** [spikto/SoustitreDownloader#12]
Bonsoir,

J'ai pu tester cette dernières version avec Betaserie et franchement elle fonctionnait vraiment au top au début, juste radicalement efficace ! Mais assez rapidement, me voilà avec une horde de fichier SRT et avec comme contenu "Page not found."

Avez vous une idée ?

**Comment by spikto** [comment]
Salut,

Je viens de rajouter une nouvelle version qui devrais corriger les problèmes que vous rencontrez.

N'hésitez pas à me faire un retour.

**Comment by Kazfr** [comment]
Un grand merci bien en retard :)
