### ISSUE TITLE
Ss titres anglais

### ISSUE THREAD

**Issue by yanoutt** [spikto/SoustitreDownloader#9]
Peux tu nous dire comment on peut faire pour changer la langue des sous titres stp

**Comment by spikto** [comment]
J'ai rajouté un 6ème argument qui permet de choisir parmi 4 langues pour l'instant.
Par contre, je te laisse tester, je n'ai pas encore eu le temps.

**Comment by yanoutt** [comment]
PHP Warning:  Missing argument 1 for sourceSubtitle::__construct(), called in /home/pi/SoustitreDownloader.php on line 283 and defined in /home/pi/SoustitreDownloader.php on line 237
PHP Notice:  Undefined variable: search in /home/pi/SoustitreDownloader.php on line 238
PHP Notice:  Trying to get property of non-object in /home/pi/SoustitreDownloader.php on line 294
Marvels Agents Of S H I E L D S02E11 : Aucun sous-titre trouvé

**Comment by yanoutt** [comment]
J'ai cherché un peu mais je comprend pas tout !!!!

**Comment by spikto** [comment]
J'ai corrigé, le problème que tu as, je n'ai toujours pas eu le temps de tester.
Je devrais pouvoir ce soir ou demain, donc en attendant n'hésites pas à me transmettre tes erreurs.

**Comment by yanoutt** [comment]
Ca cherche toujours en francais peux importe l'argument

**Comment by spikto** [comment]
Il faut bien que la langue soit le 6ème paramètres sinon le français sera choisi par default.
Peux-tu me donner ta commande pour voir ce qui peux clocher ?

**Comment by yanoutt** [comment]
php SoustitreDownloader.php /media/DDUSB/complete/Series/ [/media/DDUSB/complete/Series/ [f [ [ [en]]]]]

**Comment by spikto** [comment]
Ah, tu n'a pas du utiliser souvent des lignes de commande. Les crochets dans une ligne de commande veulent dire que ce sont des paramètres optionnels.
Tu dois donc plutôt écrire : php SoustitreDownloader.php /media/DDUSB/complete/Series/ /media/DDUSB/complete/Series/ f '' '' en
Tiens moi au courant, si ça marche avec cette commande.

**Comment by yanoutt** [comment]
ok parfait, je ne savais pas comment éviter les arguments que j n'utilise pas: il faut donc ' ' .
Un petit truc pour cette série :Marvels.Agents.of.S.H.I.E.L.D.S02E11.HDTV.x264-KILLERS,
il me renvoie : Marvel's Agents Of S H I E L D S02E11 : Aucun sous-titre trouvé
j'ai essayer de changer des lignes dans la fonction cleanserie mais je ne trouve pas la parade car il les "." sont changée en espaces. Comment retrouver S.H.I.E.L.D.

**Comment by spikto** [comment]
J'ai fais un changement pour Marvel, re-teste cela devrait être bon.

**Comment by yanoutt** [comment]
Ok c'est parfait merci beaucoup.
